<a href="https://colab.research.google.com/github/USMS-FPK-IA-GI-2025/controle01-numpy-matplotlib-iris/blob/main/notebooks/controle_numpy_matplotlib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Contrôle 01 — Data Science avec NumPy et Matplotlib
**Master 1 — Intelligence Artificielle & Génie Informatique (FPK / USMS)**

Nom & Prénom :  adil chagri

Filière :  SIIA

Année universitaire : 2025-2026

---

**Règles :**
- Bibliothèques autorisées : NumPy, Matplotlib
- Toute autre bibliothèque est interdite
- Chaque question doit être traitée dans une cellule dédiée
- Chaque résultat doit être brièvement interprété


# Partie A — Importation du Dataset, Arrays, Premières Manipulations

### A1. Importation du dataset
Importez NumPy et Matplotlib.  
Chargez le fichier `iris.csv` avec `np.genfromtxt` (`delimiter=','`, `skip_header=1`).  
Stockez les données dans un array nommé `data` et affichez sa `shape`.


In [43]:
import numpy as np
import matplotlib.pyplot as plt
#importation du dataset
# changement du type des données au <20
data = np.genfromtxt('..\data\Iris.csv', delimiter=',', skip_header=1, dtype='<U20')

print(f"shape du dataset : {data.shape}")

shape du dataset : (150, 6)


### A2. Séparation des features et des espèces
Séparez :
- les 4 premières colonnes numériques dans un array `features`
- la dernière colonne (espèces) dans un array `species`
Utilisez le slicing.


In [44]:
#il faut changer le type des données au float 
features = data[: , 1:5].astype(float)
species = data[: , -1]
print(features)
print(species)


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

### A3. Indexing
Affichez les 5 premières lignes de `features` en utilisant l’indexing.


In [45]:
#affichage des 5 premiers elements
print(features[:5])



[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


### A4. Extraction d’une colonne
Créez un array `sepal_length` contenant uniquement la première colonne de `features`.  
Affichez sa `size` et son `dtype`.


In [46]:
#affectation du premiere colonne au sepal_lenght
sepal_length= features[: , 0]
print(f"Size : {sepal_length.size}")
print(f"Dtype : {sepal_length.dtype}")

Size : 150
Dtype : float64


### A5. Slicing par espèce
Utilisez le slicing pour extraire les 50 premières lignes correspondant à l’espèce *Setosa*.  
Stockez-les dans `setosa_features`.


In [47]:
setosa_features = features[:50]
print(setosa_features.shape)
print(setosa_features)


(50, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]]


# Partie B — Statistiques Basiques et Opérations Mathématiques

### B6. Moyenne par colonne
Calculez la moyenne de chaque colonne de `features` avec `np.mean(axis=0)`.


In [48]:
#calcule de la moyenne des features avec axis=0 pour la selection verticale
mean_features = np.mean(features , axis=0)
print(f"Moyennes par feature : {mean_features}")

Moyennes par feature : [5.84333333 3.054      3.75866667 1.19866667]


### B7. Min et Max
Trouvez la valeur minimale et maximale de la longueur des pétales.


In [49]:
min_val = np.min(features[: , 2])
max_val = np.max(features[: , 2])
print(f"la valeur minimale {min_val}")
print(f"la valeur maximale {max_val}")

la valeur minimale 1.0
la valeur maximale 6.9


### B9. Normalisation
Normalisez les longueurs des pétales en les divisant par leur maximum.
Stockez le résultat dans `normalized_petals`.


In [50]:
#normalisation des longueurs des pétales
normalized_petals = features[: ,2]/max_val
print(f"les longueurs des pétales normaliser{normalized_petals} ")


les longueurs des pétales normaliser[0.20289855 0.20289855 0.1884058  0.2173913  0.20289855 0.24637681
 0.20289855 0.2173913  0.20289855 0.2173913  0.2173913  0.23188406
 0.20289855 0.15942029 0.17391304 0.2173913  0.1884058  0.20289855
 0.24637681 0.2173913  0.24637681 0.2173913  0.14492754 0.24637681
 0.27536232 0.23188406 0.23188406 0.2173913  0.20289855 0.23188406
 0.23188406 0.2173913  0.2173913  0.20289855 0.2173913  0.17391304
 0.1884058  0.2173913  0.1884058  0.2173913  0.1884058  0.1884058
 0.1884058  0.23188406 0.27536232 0.20289855 0.23188406 0.20289855
 0.2173913  0.20289855 0.68115942 0.65217391 0.71014493 0.57971014
 0.66666667 0.65217391 0.68115942 0.47826087 0.66666667 0.56521739
 0.50724638 0.60869565 0.57971014 0.68115942 0.52173913 0.63768116
 0.65217391 0.5942029  0.65217391 0.56521739 0.69565217 0.57971014
 0.71014493 0.68115942 0.62318841 0.63768116 0.69565217 0.72463768
 0.65217391 0.50724638 0.55072464 0.53623188 0.56521739 0.73913043
 0.65217391 0.65217391 0.68

### B10. Somme cumulée
Calculez la somme cumulée des largeurs des pétales pour Versicolor.
Affichez les 10 premières valeurs.


In [51]:
#calcule du somme cumulee avec np.cumsum
versicolor_petal_width = features[50:100 , 3]
cumsum_versicolor = np.cumsum(versicolor_petal_width)
print(f"cumsum du 10 premieres val{cumsum_versicolor[:10]}")

cumsum du 10 premieres val[ 1.4  2.9  4.4  5.7  7.2  8.5 10.1 11.1 12.4 13.8]


### B10. Somme cumulée
Calculez la somme cumulée des largeurs des pétales pour Versicolor.
Affichez les 10 premières valeurs.


In [52]:
#calcule du somme cumulee avec np.cumsum
versicolor_petal_width = features[50:100 , 3]
cumsum_versicolor = np.cumsum(versicolor_petal_width)
print(f"cumsum du 10 premieres val{cumsum_versicolor[:10]}")

cumsum du 10 premieres val[ 1.4  2.9  4.4  5.7  7.2  8.5 10.1 11.1 12.4 13.8]


# Partie C — Transformations Avancées avec NumPy

### C11. Espèces uniques
Listez les espèces uniques avec `np.unique` et comptez leurs occurrences.


In [53]:
#calcule l'occurance des espèces
#np.unique return deux valeurs les especes et le nombre d'occurance de chaque espece
unique_species , counts = np.unique(species , return_counts=True)
print(f"Espèces : {unique_species}")
print(f"Counts :{counts}")




Espèces : ['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']
Counts :[50 50 50]


### C12. Reshape par espèce
Transformez `features` en un array de forme `(3, 50, 4)` nommé `features_by_species`.


In [54]:
#transformation du forme  d'array 
features_by_species = features.reshape(3,50,4)
print(f"features by species : {features_by_species}")
#affichage de la forme de l'array pour assurer la transformation
print(features_by_species.shape)


features by species : [[[5.1 3.5 1.4 0.2]
  [4.9 3.  1.4 0.2]
  [4.7 3.2 1.3 0.2]
  [4.6 3.1 1.5 0.2]
  [5.  3.6 1.4 0.2]
  [5.4 3.9 1.7 0.4]
  [4.6 3.4 1.4 0.3]
  [5.  3.4 1.5 0.2]
  [4.4 2.9 1.4 0.2]
  [4.9 3.1 1.5 0.1]
  [5.4 3.7 1.5 0.2]
  [4.8 3.4 1.6 0.2]
  [4.8 3.  1.4 0.1]
  [4.3 3.  1.1 0.1]
  [5.8 4.  1.2 0.2]
  [5.7 4.4 1.5 0.4]
  [5.4 3.9 1.3 0.4]
  [5.1 3.5 1.4 0.3]
  [5.7 3.8 1.7 0.3]
  [5.1 3.8 1.5 0.3]
  [5.4 3.4 1.7 0.2]
  [5.1 3.7 1.5 0.4]
  [4.6 3.6 1.  0.2]
  [5.1 3.3 1.7 0.5]
  [4.8 3.4 1.9 0.2]
  [5.  3.  1.6 0.2]
  [5.  3.4 1.6 0.4]
  [5.2 3.5 1.5 0.2]
  [5.2 3.4 1.4 0.2]
  [4.7 3.2 1.6 0.2]
  [4.8 3.1 1.6 0.2]
  [5.4 3.4 1.5 0.4]
  [5.2 4.1 1.5 0.1]
  [5.5 4.2 1.4 0.2]
  [4.9 3.1 1.5 0.1]
  [5.  3.2 1.2 0.2]
  [5.5 3.5 1.3 0.2]
  [4.9 3.1 1.5 0.1]
  [4.4 3.  1.3 0.2]
  [5.1 3.4 1.5 0.2]
  [5.  3.5 1.3 0.3]
  [4.5 2.3 1.3 0.3]
  [4.4 3.2 1.3 0.2]
  [5.  3.5 1.6 0.6]
  [5.1 3.8 1.9 0.4]
  [4.8 3.  1.4 0.3]
  [5.1 3.8 1.6 0.2]
  [4.6 3.2 1.4 0.2]
  [5.3 3.7 1.5 0.2

### C13. Concaténation
Concaténez horizontalement les moyennes par colonne avec un array de zéros.


In [55]:
#concatenation du array des moyennes avec un array de zeros horizontalement(axis=1)
mean_colone = np.concatenate((mean_features.reshape(4,1) , np.zeros((4,1))) , axis=1)
print("Concaténation (Moyenne | Zéros) :")
print(mean_colone)


Concaténation (Moyenne | Zéros) :
[[5.84333333 0.        ]
 [3.054      0.        ]
 [3.75866667 0.        ]
 [1.19866667 0.        ]]


### C14. Data cleaning (simulation)
Simulez des valeurs NaN et remplacez-les avec `np.nan_to_num`.


In [73]:
#maintenant on simulez des valeurs nan pour simulez le data cleaning 
#premierement on va faire une copy du dataset 
dirty_data = features.copy()
#maintenant on va simuler des valeurs nan
dirty_data[0,0]=np.nan
#maintenant on va changer les valeurs nan par 0.0
clean_data=np.nan_to_num(dirty_data , nan=0.0)
print(f"the data after cleaning : {clean_data}")

the data after cleaning : [[0.  3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4

### C15. Broadcasting
Ajoutez 1 à toutes les valeurs de la première colonne de `features`.


In [75]:
#ajout des 1 dans la premiere colonne
features_plus_one = features[: , 0]+1
print(f"Valeurs originales (5 premières) : {features[:5, 0]}")
print(f"Valeurs +1 (5 premières)         : {features_plus_one[:5]}")


Valeurs originales (5 premières) : [5.1 4.9 4.7 4.6 5. ]
Valeurs +1 (5 premières)         : [6.1 5.9 5.7 5.6 6. ]


### C16. np.where
Créez un array binaire indiquant si la longueur des pétales est supérieure à 4.0.


In [77]:
#faire un masque pour les petales supérieurs a 4
petales_array = np.where(features[: , 2] > 4.0 ,1 ,0)
print(f"Masque binaire (10 premiers) : {petales_array[:150]}")

Masque binaire (10 premiers) : [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 1 1 1 0 1 0 0 1 0 1 0 1 1 1 1 0 1 0 1 1
 1 1 1 1 1 0 0 0 0 1 1 1 1 1 1 0 1 1 0 0 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1]


# Partie D — Visualisation avec Matplotlib (Plots Simples)

### D17. Line plot
Line plot des longueurs des sépales pour les 50 premières fleurs.


In [59]:
# Votre code ici


### D18. Scatter plot
Scatter plot : longueur vs largeur des pétales.


In [60]:
# Votre code ici


### D19. Bar chart
Bar chart des moyennes des quatre caractéristiques.


In [61]:
# Votre code ici


### D20. Histogram
Histogramme de la largeur des sépales (10 bins).


In [62]:
# Votre code ici


### D21. Boxplot par espèce
Boxplot des longueurs des pétales par espèce.


In [63]:
# Votre code ici


# Partie E — Visualisations Avancées

### E22. Subplots comparatifs
Deux scatter plots côte à côte : Setosa vs Versicolor.


In [64]:
# Votre code ici


### E23. Grille 2x2
Histogrammes des 4 caractéristiques avec `plt.subplots(2,2)`.


In [65]:
# Votre code ici


### E24. Bar chart avec error bars
Moyennes par espèce avec écart-type.


In [66]:
# Votre code ici


### E25. Scatter coloré par espèce
Scatter plot avec couleurs par espèce.


In [67]:
# Votre code ici


### E26. Line plot superposé
Cumsum des largeurs des pétales par espèce.


In [68]:
# Votre code ici


# Partie F — Mini-Analyse Finale

### F27. Corrélations
Calculez la matrice de corrélation avec `np.corrcoef`.


In [69]:
# Votre code ici


### F28. Visualisation des corrélations
Visualisez les corrélations sous forme de bar chart ou scatter.


In [70]:
# Votre code ici


### F29. Variance par espèce
Identifiez l’espèce avec la plus grande variance globale et visualisez ses distributions.


In [71]:
# Votre code ici


### F30. Conclusion
Rédigez une conclusion contenant **3 insights** issus de votre analyse.


1) ...
2) ...
3) ...